name: React Vite CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: balancewell  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
